name: Deploy Angular to GH Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # necesario para empujar a gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i

      - name: Build (prod con base-href del repo)
        run: npm run build -- --configuration production --base-href "/dnd-dm-client/"

      - name: Install angular-cli-ghpages
        run: npm i -g angular-cli-ghpages

      - name: Deploy to GH Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npx angular-cli-ghpages \
            --dir=dist/dnd-dm-client/browser \
            --branch=gh-pages \
            --no-silent \
            --repo="https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" \
            --message="deploy: ${{ github.sha }}"
